#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPocoIO.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using AutoPocoIO.Dashboard.ViewModels;
    using AutoPocoIO.Middleware;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class DataDictionaryPage : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n\r\n");




WriteLiteral(@"
<div class=""container pt-4 mt-5"">
    <h1>
        Connectors
    </h1>
    <hr />
    <table class=""table table-hover selectable mt-5"">
        <thead>
            <tr class=""table-secondary"">
                <th>Connector Name</th>
                <th>Connector Type</th>
                <th>Server</th>
                <th>Database Name</th>
                <th>Schema</th>
            </tr>
        </thead>
        <tbody>
");


             foreach (var row in (IEnumerable<ConnectorViewModel>)ViewBag["Connectors"])
            {

WriteLiteral("                <tr class=\"clickable-row\" data-url=\"");


                                               Write(TransformUrl("/DataDictionary/Schema/"));


                                                                                       Write(row.Id);

WriteLiteral("\">\r\n                    <td>");


                   Write(row.Name);

WriteLiteral("</td>\r\n                    <td>");


                   Write(row.ResourceType.Split('.').Last());

WriteLiteral("</td>\r\n                    <td>");


                   Write(row.DataSource);

WriteLiteral("</td>\r\n                    <td>");


                   Write(row.InitialCatalog);

WriteLiteral("</td>\r\n                    <td>");


                   Write(row.Schema);

WriteLiteral("</td>\r\n                </tr>\r\n");


            }

WriteLiteral("        </tbody>\r\n    </table>\r\n</div>\r\n\r\n");


DefineSection("script", () => {

WriteLiteral("\r\n    <script>\r\n        jQuery(document).ready(function ($) {\r\n            $(\".cl" +
"ickable-row\").click(function () {\r\n                window.location = $(this).dat" +
"a(\"url\");\r\n            });\r\n        });\r\n    </script>\r\n");


});


        }
    }
}
#pragma warning restore 1591
