#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPocoIO.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using AutoPocoIO.Dashboard.ViewModels;
    using AutoPocoIO.Middleware;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class ConnectorForm : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n\r\n");




WriteLiteral("\r\n<div class=\"container pt-4 mt-5\">\r\n    <h1>Create Connector</h1>\r\n    <hr />\r\n " +
"   <form class=\"mt-5\" method=\"post\">\r\n        <input type=\"hidden\" name=\"id\" val" +
"ue=\"");


                                          Write(GetViewBagValue<ConnectorViewModel>("model").Id);

WriteLiteral(@""" />
        <div class=""form-group"">
            <label for=""connectorName"">Connector Name</label>
            <input type=""text"" class=""form-control"" name=""connectorName"" aria-describedby=""connectorHelp"" placeholder=""e.g. Adventureworks""
                   value=""");


                      Write(GetViewBagValue<ConnectorViewModel>("model").Name);

WriteLiteral("\" />\r\n            <small id=\"connectorHelp\" class=\"form-text text-muted\">This is " +
"the name used in all calls to this schema</small>\r\n            <div class=\"error" +
"Message\"><span class=\"text-danger\">");


                                                           Write(GetError("errors", nameof(ConnectorViewModel.Name)));

WriteLiteral("</span></div>\r\n        </div>\r\n        <div class=\"form-group\">\r\n            <lab" +
"el for=\"serverName\">Servername</label>\r\n            <input type=\"text\" class=\"fo" +
"rm-control\" name=\"serverName\" placeholder=\"Database Server Name\"\r\n              " +
"     value=\"");


                      Write(GetViewBagValue<ConnectorViewModel>("model").DataSource);

WriteLiteral("\" />\r\n            <div class=\"errorMessage\"><span class=\"text-danger\">");


                                                           Write(GetError("errors", nameof(ConnectorViewModel.DataSource)));

WriteLiteral("</span></div>\r\n        </div>\r\n        <div class=\"form-group\">\r\n            <lab" +
"el for=\"databaseName\">Database Name</label>\r\n            <input type=\"text\" clas" +
"s=\"form-control\" name=\"databaseName\"\r\n                   value=\"");


                      Write(GetViewBagValue<ConnectorViewModel>("model").InitialCatalog);

WriteLiteral("\" />\r\n            <div class=\"errorMessage\"><span class=\"text-danger\">");


                                                           Write(GetError("errors", nameof(ConnectorViewModel.InitialCatalog)));

WriteLiteral("</span></div>\r\n        </div>\r\n        <div class=\"form-group\">\r\n            <lab" +
"el for=\"schema\">Schema</label>\r\n            <input type=\"text\" class=\"form-contr" +
"ol\" name=\"schema\"\r\n                   value=\"");


                      Write(GetViewBagValue<ConnectorViewModel>("model").Schema);

WriteLiteral("\" />\r\n            <div class=\"errorMessage\"><span class=\"text-danger\">");


                                                           Write(GetError("errors", nameof(ConnectorViewModel.Schema)));

WriteLiteral("</span></div>\r\n        </div>\r\n        <div class=\"form-group\">\r\n            <lab" +
"el for=\"userId\">Database User Account Name</label>\r\n            <input type=\"tex" +
"t\" class=\"form-control\" name=\"userId\"\r\n                   value=\"");


                      Write(GetViewBagValue<ConnectorViewModel>("model").UserId);

WriteLiteral("\" />\r\n            <div class=\"errorMessage\"><span class=\"text-danger\">");


                                                           Write(GetError("errors", nameof(ConnectorViewModel.UserId)));

WriteLiteral("</span></div>\r\n        </div>\r\n        <div class=\"form-group\">\r\n            <lab" +
"el for=\"password\">Database User Account Password</label>\r\n            <input typ" +
"e=\"password\" class=\"form-control\" name=\"password\"\r\n                   value=\"");


                      Write(GetViewBagValue<ConnectorViewModel>("model").Password);

WriteLiteral("\" />\r\n            <div class=\"errorMessage\"><span class=\"text-danger\">");


                                                           Write(GetError("errors", nameof(ConnectorViewModel.Password)));

WriteLiteral("</span></div>\r\n        </div>\r\n        <div class=\"form-group\">\r\n            <lab" +
"el for=\"recordLimit\">Maximum Records Returned</label>\r\n            <input type=\"" +
"text\" class=\"form-control\" name=\"recordLimit\"\r\n                   value=\"");


                      Write(GetViewBagValue<ConnectorViewModel>("model").RecordLimit);

WriteLiteral("\" />\r\n            <div class=\"errorMessage\"><span class=\"text-danger\">");


                                                           Write(GetError("errors", nameof(ConnectorViewModel.RecordLimit)));

WriteLiteral("</span></div>\r\n        </div>\r\n        <div class=\"form-check\">\r\n            <inp" +
"ut type=\"checkbox\" class=\"form-check-input\" name=\"isEnabled\" ");


                                                                         Write(GetViewBagValue<ConnectorViewModel>("model").IsActive ? "checked" : "");

WriteLiteral(">\r\n            <label class=\"form-check-label\" for=\"isEnabled\">Active</label>\r\n  " +
"      </div>\r\n        <button type=\"submit\" class=\"btn btn-info mt-3\">Submit</bu" +
"tton>\r\n    </form>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
