#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPocoIO.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using AutoPocoIO.Middleware;
    using AutoPocoIO.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class ConnectorsPage : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n\r\n");




WriteLiteral("\r\n<div class=\"container pt-4 mt-5\">\r\n    <h1>\r\n        <div class=\"btn-group btn-" +
"group-toggle mt-2\" style=\"float: right !important\" data-toggle=\"buttons\">\r\n     " +
"       <label class=\"btn btn-info active\" onclick=\"window.location=\'");


                                                                    Write(TransformUrl("/Connectors/Connector/New"));

WriteLiteral(@"'"">
                <input type=""radio"" name=""options"" id=""option1"" autocomplete=""off"" checked > + Create Connector
            </label>
        </div>
        Connectors
    </h1>
    <hr />
    <table class=""table table-hover mt-5"">
        <thead>
            <tr class=""table-secondary"">
                <th scope=""col"">Name</th>
                <th scope=""col"">Server</th>
                <th scope=""col"">Database</th>
                <th scope=""col"">Schema</th>
                <th scope=""col"">User</th>
            </tr>
        </thead>
        <tbody>
");


             foreach (var row in (IEnumerable<Connector>)ViewBag["Connectors"])
            {
                

WriteLiteral("                <tr>\r\n                    <th scope=\"row\"><a href=\"");


                                        Write(TransformUrl("/Connectors/Connector/" + row.Id));

WriteLiteral("\">");


                                                                                          Write(row.Name);

WriteLiteral("</a></th>\r\n                    <td>");


                   Write(row.DataSource);

WriteLiteral("</td>\r\n                    <td>");


                   Write(row.InitialCatalog);

WriteLiteral("</td>\r\n                    <td>");


                   Write(row.Schema);

WriteLiteral("</td>\r\n                    <td>");


                   Write(row.UserId);

WriteLiteral("</td>\r\n                </tr>\r\n");


            }

WriteLiteral("        </tbody>\r\n    </table>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
