#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPocoIO.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using AutoPocoIO.Dashboard.ViewModels;
    using AutoPocoIO.Middleware;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class ConnectorForm : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n\r\n");




WriteLiteral("\r\n<div class=\"container pt-4 mt-5\">\r\n    <h1>Create Connector</h1>\r\n    <hr />\r\n " +
"   <form class=\"mt-5\" method=\"post\">\r\n        <input type=\"hidden\" name=\"id\" val" +
"ue=\"");


                                          Write(GetViewBagValue<ConnectorViewModel>("model").Id);

WriteLiteral(@""" />
        <div class=""form-group"">
            <label for=""connectorName"">Connector Name</label>
            <input type=""text"" class=""form-control"" name=""connectorName"" aria-describedby=""connectorHelp"" placeholder=""e.g. Adventureworks""
                   value=""");


                      Write(GetViewBagValue<ConnectorViewModel>("model").Name);

WriteLiteral(@""" />
            <small id=""connectorHelp"" class=""form-text text-muted"">This is the name used in all calls to this schema</small>
        </div>
        <div class=""form-group"">
            <label for=""serverName"">Servername</label>
            <input type=""text"" class=""form-control"" name=""serverName"" placeholder=""Database Server Name""
                   value=""");


                      Write(GetViewBagValue<ConnectorViewModel>("model").DataSource);

WriteLiteral("\" />\r\n        </div>\r\n        <div class=\"form-group\">\r\n            <label for=\"d" +
"atabaseName\">\"Database Name</label>\r\n            <input type=\"text\" class=\"form-" +
"control\" name=\"databaseName\"\r\n                   value=\"");


                      Write(GetViewBagValue<ConnectorViewModel>("model").InitialCatalog);

WriteLiteral("\" />\r\n        </div>\r\n        <div class=\"form-group\">\r\n            <label for=\"s" +
"chema\">Schema</label>\r\n            <input type=\"text\" class=\"form-control\" name=" +
"\"schema\"\r\n                   value=\"");


                      Write(GetViewBagValue<ConnectorViewModel>("model").Schema);

WriteLiteral("\" />\r\n        </div>\r\n        <div class=\"form-group\">\r\n            <label for=\"u" +
"serId\">Database User Account Name</label>\r\n            <input type=\"text\" class=" +
"\"form-control\" name=\"userId\"\r\n                   value=\"");


                      Write(GetViewBagValue<ConnectorViewModel>("model").UserId);

WriteLiteral("\" />\r\n        </div>\r\n        <div class=\"form-group\">\r\n            <label for=\"p" +
"assword\">Database User Account Password</label>\r\n            <input type=\"text\" " +
"class=\"form-control\" name=\"password\"\r\n                   value=\"");


                      Write(GetViewBagValue<ConnectorViewModel>("model").Password);

WriteLiteral("\" />\r\n        </div>\r\n        <div class=\"form-group\">\r\n            <label for=\"r" +
"ecordLimit\">Maximum Records Returned</label>\r\n            <input type=\"text\" cla" +
"ss=\"form-control\" name=\"recordLimit\"\r\n                   value=\"");


                      Write(GetViewBagValue<ConnectorViewModel>("model").RecordLimit);

WriteLiteral(@""" />
        </div>
        <div class=""form-check"">
            <input type=""checkbox"" class=""form-check-input"" id=""isEnabled"">
            <label class=""form-check-label"" for=""isEnabledcheckbox"">Active</label>
        </div>
        <button type=""submit"" class=""btn btn-info mt-3"">Submit</button>
    </form>
</div>
");


        }
    }
}
#pragma warning restore 1591
