#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPocoIO.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using AutoPocoIO.Dashboard.ViewModels;
    using AutoPocoIO.Middleware;
    using AutoPocoIO.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class ObjectDetailsPage : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n\r\n");




WriteLiteral("\r\n");


WriteLiteral("\r\n");


  
    var Model = (TableDefinition)ViewBag["model"];
    var Navs = (IEnumerable<NavigationPropertyViewModel>)ViewBag["navs"];


WriteLiteral("\r\n    <div class=\"container pt-4 mt-5\">\r\n        <h2>\r\n            Data Dictionar" +
"y - ");


                         Write(Model.Name);

WriteLiteral(@"
        </h2>
        <hr />
        <table class=""table table-hover selectable mt-3"">
            <thead>
                <tr class=""table-secondary"">
                    <th>Column Name</th>
                    <th>Type</th>
                    <th>Primary Key</th>
                    <th>Forigen Key</th>
                </tr>
            </thead>
            <tbody>
");


                 foreach (var row in Model.Columns)
                {

WriteLiteral("                    <tr>\r\n                        <td>");


                       Write(row.Name);

WriteLiteral("</td>\r\n                        <td>");


                       Write(row.Type);

WriteLiteral("</td>\r\n                        <td>");


                        Write(row.IsPrimaryKey ? "Yes" : "No");

WriteLiteral("</td>\r\n                        <td>");


                        Write(row.IsForigenKey ? "Yes" : "No");

WriteLiteral("</td>\r\n                    </tr>\r\n");


                }

WriteLiteral(@"            </tbody>
        </table>
        <table class=""table table-hover selectable mt-3"">
            <thead>
                <tr class=""table-secondary"">
                    <th>Navigation Property</th>
                    <th>Relationship Type</th>
                    <th>Referenced Schema</th>
                    <th>Referenced Table</th>
                </tr>
            </thead>
            <tbody>
");


                 foreach (var row in Navs)
                {

WriteLiteral("                <tr>\r\n                    <td>");


                   Write(row.Name);

WriteLiteral("</td>\r\n                    <td>");


                   Write(row.Relationship);

WriteLiteral("</td>\r\n                    <td>");


                   Write(row.ReferencedSchema);

WriteLiteral("</td>\r\n                    <td>");


                   Write(row.ReferencedTable);

WriteLiteral("</td>\r\n                </tr>\r\n");


                }

WriteLiteral("            </tbody>\r\n        </table>\r\n\r\n    </div>\r\n");


        }
    }
}
#pragma warning restore 1591
