#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPocoIO.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using AutoPocoIO.Dashboard.ViewModels;
    using AutoPocoIO.Middleware;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class RequestHistoryPage : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n\r\n");




WriteLiteral(@"
    <div class=""container pt-4 mt-5"">
        <h1>
            Request History
        </h1>
        <hr />
        <table class=""table table-hover mt-5"">
            <thead>
                <tr class=""table-secondary"">
                    <th scope=""col"">Request Time</th>
                    <th scope=""col"">Type</th>
                    <th scope=""col"">Requester</th>
                    <th scope=""col"">Connector</th>
                    <th scope=""col"">Resouce</th>
                    <th scope=""col"">Resource Key</th>
                    <th scope=""col"">Status</th>
                </tr>
            </thead>
            <tbody>
");


                 foreach (var row in (IEnumerable<RequestGridViewModel>)ViewBag["requests"])
                {

WriteLiteral("                <tr>\r\n                    <th scope=\"row\">");


                               Write(row.DateTimeUtc);

WriteLiteral("</th>\r\n                    <td>\r\n                        <span class=\"badge badge" +
"-pill\" style=\"color:#fff;background-color:\r\n");


                                 switch (row.RequestType)
                                {
                                    case "GET": 
                                            Write("#1b5168");

                                                            
                                        break;
                                    case "DELETE": 
                                               Write( "#C0324A");

                                                                
                                        break;
                                    case "POST": 
                                             Write( "#1B7B7F");

                                                              
                                        break;
                                    case "PUT": 
                                            Write("#ffba00");

                                                            
                                        break;
                                }
WriteLiteral(";\">\r\n                            ");


                       Write(row.RequestType);

WriteLiteral("\r\n                        </span>\r\n                    </td>\r\n                   " +
" <td>");


                   Write(row.Requester);

WriteLiteral("</td>\r\n                    <td>");


                   Write(row.Connector);

WriteLiteral("</td>\r\n                    <td>");


                   Write(row.Resource);

WriteLiteral("</td>\r\n                    <td>");


                   Write(row.ResourceId);


                                       WriteLiteral("</td>\r\n                    <td style=\"color: ");

                                       if (row.Status == "HTTP 200 : OK" || row.Status == "HTTP 302 : Found") { 
                                                                                                            Write("green");

                                                                                                                          } else { 
                                                                                                                               Write("red");

                                                                                                                                           }
WriteLiteral(" \">");


                                                                                                                                           Write(row.Status);

WriteLiteral("</td>\r\n                </tr>\r\n");


                }

WriteLiteral("            </tbody>\r\n        </table>\r\n    </div>");


        }
    }
}
#pragma warning restore 1591
