version: '1.0.{build}'
image: Visual Studio 2019

shallow_clone: true

environment:
   VERSION: 1.0.0     
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
    # Display minimal restore text
  - cmd: dotnet restore ./sln/AutoPocoIO.sln --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet build ./sln/AutoPocoIO.sln
  - cmd: dotnet pack src/AutoPocoIO/AutoPocoIO.csproj -p:PackageVersion="%VERSION%-beta.%APPVEYOR_BUILD_NUMBER%"
  - cmd: dotnet pack src/AutoPocoIO.MsSql/AutoPocoIO.MsSql.csproj -p:PackageVersion="%VERSION%-beta.%APPVEYOR_BUILD_NUMBER%"
test_script:
  # run the unit tests (requires changing into the test directory)
  - cmd: cd tests
  - cmd: dotnet test ./AutoPocoIO.test/AutoPocoIO.test.csproj  --framework net461 --logger trx
  - cmd: dotnet test ./AutoPocoIO.AspNet.test/AutoPocoIO.AspNet.test.csproj  --framework net461 --logger trx
  - cmd: dotnet test ./AutoPocoIO.MsSql.test/AutoPocoIO.MsSql.test.csproj  --framework net461 --logger trx
  - cmd: dotnet test ./AutoPocoIO.test/AutoPocoIO.test.csproj  --framework netcoreapp2.2 --logger trx
  - cmd: dotnet test ./AutoPocoIO.AspNetCore.test/AutoPocoIO.AspNetCore.test.csproj  --framework netcoreapp2.2 --logger trx
  - cmd: dotnet test ./AutoPocoIO.MsSql.test/AutoPocoIO.MsSql.test.csproj  --framework netcoreapp2.2 --logger trx

artifacts:
  - path: '**\*.nupkg' # find all NuGet packages recursively
deploy:
  - provider : NuGet
    server: https://nuget.pkg.github.com/AutoPocoIO/index.json
    artifact: /.nupkg/
    username:
       secure: RjsXxaVLs5C3lpq67rHM9g==
    api_key:
       secure: MT0+TYT7sH+F3qYM33HKuYp88ev2TgNsHLKO9R4G4F9s9iG2NyyJbi4aaQtfPT6+
    on:
       branch: master    
