//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPocoIO.Constants {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoPocoIO.Constants.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DashboardAppId is required and must be a GUID string..
        /// </summary>
        public static string ApplicationIdMustBeGuid {
            get {
                return ResourceManager.GetString("ApplicationIdMustBeGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error finding Application Id..
        /// </summary>
        public static string ApplicationIdNotFound {
            get {
                return ResourceManager.GetString("ApplicationIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assemblies found with no types loaded..
        /// </summary>
        public static string AssemblyFoundWithNoTypes {
            get {
                return ResourceManager.GetString("AssemblyFoundWithNoTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter excpected to be &quot;U&quot; or &quot;V&quot;.
        /// </summary>
        public static string CharToDbObjecType {
            get {
                return ResourceManager.GetString("CharToDbObjecType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DbAdapter type requested is not found..
        /// </summary>
        public static string DbAdapterNotFound {
            get {
                return ResourceManager.GetString("DbAdapterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Db object type must be a Table or View..
        /// </summary>
        public static string DbObjectType {
            get {
                return ResourceManager.GetString("DbObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is expecting a {0} database but it is not registered in Startup..
        /// </summary>
        public static string DbTypeNotRegistered {
            get {
                return ResourceManager.GetString("DbTypeNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EF Core does not support HierarchyId types yet..
        /// </summary>
        public static string HierarchyIdNotSupported {
            get {
                return ResourceManager.GetString("HierarchyIdNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Sql Data Type..
        /// </summary>
        public static string InvalidSqlDataType {
            get {
                return ResourceManager.GetString("InvalidSqlDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load manifest resource stream..
        /// </summary>
        public static string LoadDashboardCss {
            get {
                return ResourceManager.GetString("LoadDashboardCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middleware path must start with a &apos;/&apos; followed by one or more characters..
        /// </summary>
        public static string MiddlewarePath {
            get {
                return ResourceManager.GetString("MiddlewarePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is expecting a MySQL database but it is not registered in Startup..
        /// </summary>
        public static string MySqlNotRegistered {
            get {
                return ResourceManager.GetString("MySqlNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No database types registered. Setup at least one database type in startup..
        /// </summary>
        public static string NoDbTypesRegistered {
            get {
                return ResourceManager.GetString("NoDbTypesRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is expecting a Oracle database but it is not registered in Startup..
        /// </summary>
        public static string OracleNotRegistered {
            get {
                return ResourceManager.GetString("OracleNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested service was not registered in startup..
        /// </summary>
        public static string ServiceNotRegistered {
            get {
                return ResourceManager.GetString("ServiceNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is expecting a SQL database but it is not registered in Startup..
        /// </summary>
        public static string SqlNotRegistered {
            get {
                return ResourceManager.GetString("SqlNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type not a sequence..
        /// </summary>
        public static string TypeNotSequence {
            get {
                return ResourceManager.GetString("TypeNotSequence", resourceCulture);
            }
        }
    }
}
