version: 2.1

orbs:
  win: circleci/windows@2.2.0

executors:
  win-executor:
     win/default  
jobs:      
  test-framework:
    executor: win-executor
    steps:
       - checkout
       - restore_cache:
          keys:
            - dotnet-packages-{{ checksum "tests/AutoPocoIO.test/AutoPocoIO.test.csproj" }}-{{ checksum "tests/AutoPocoIO.AspNet.test/AutoPocoIO.AspNet.test.csproj" }}-{{ checksum "tests/AutoPocoIO.MsSql.test/AutoPocoIO.MsSql.test.csproj" }}
       - run:
          name: "Restore packages"
          command: dotnet restore sln/AutoPocoIO.sln
       - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-{{ checksum "tests/AutoPocoIO.test/AutoPocoIO.test.csproj" }}-{{ checksum "tests/AutoPocoIO.AspNet.test/AutoPocoIO.AspNet.test.csproj" }}-{{ checksum "tests/AutoPocoIO.MsSql.test/AutoPocoIO.MsSql.test.csproj" }}
       - run:
          name: "Test .NET 4.6.1"
          command:  dotnet test tests/AutoPocoIO.test/AutoPocoIO.test.csproj --results-directory:test_coverage --collect:"Code Coverage" --framework net461 --logger trx
       - run:
          name: "Test .NET 4.6.1 Specific Tests"
          command:  dotnet test tests/AutoPocoIO.AspNet.test/AutoPocoIO.AspNet.test.csproj --results-directory:test_coverage --collect:"Code Coverage" --framework net461 --logger trx
       - run:
          name: "Test .NET 4.6.1 MsSql Tests"
          command:  dotnet test tests/AutoPocoIO.MsSql.test/AutoPocoIO.MsSql.test.csproj --results-directory:test_coverage --collect:"Code Coverage" --framework net461 --logger trx
       - store_artifacts:
          path: C:\Users\circleci\project\test_coverage
       

  test-core:
    executor: win-executor
    steps:
       - checkout
       - restore_cache:
          keys:
            - dotnet-packages-{{ checksum "tests/AutoPocoIO.test/AutoPocoIO.test.csproj" }}-{{ checksum "tests/AutoPocoIO.AspNetCore.test/AutoPocoIO.AspNetCore.test.csproj" }}-{{ checksum "tests/AutoPocoIO.MsSql.test/AutoPocoIO.MsSql.test.csproj" }}
       - run:
          name: "Restore packages"
          command: dotnet restore sln/AutoPocoIO.sln
       - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-{{ checksum "tests/AutoPocoIO.test/AutoPocoIO.test.csproj" }}-{{ checksum "tests/AutoPocoIO.AspNet.test/AutoPocoIO.AspNet.test.csproj" }}-{{ checksum "tests/AutoPocoIO.MsSql.test/AutoPocoIO.MsSql.test.csproj" }}
       - run:
          name: "Test  AspNet Core 2.2"
          command:  dotnet test tests/AutoPocoIO.test/AutoPocoIO.test.csproj  --results-directory:test_coverage --collect:"Code Coverage" --framework netcoreapp2.2 --logger trx
       - run:
          name: "Test  AspNet Core 2.2 Specific Tests"
          command:  dotnet test tests/AutoPocoIO.AspNetCore.test/AutoPocoIO.AspNetCore.test.csproj  --results-directory:test_coverage --collect:"Code Coverage" --framework netcoreapp2.2 --logger trx
       - run:
          name: "Test  AspNet Core 2.2 MsSql Tests"
          command:  dotnet test tests/AutoPocoIO.MsSql.test/AutoPocoIO.MsSql.test.csproj --results-directory:test_coverage --collect:"Code Coverage" --framework netcoreapp2.2 --logger trx
  
  deploy:
    executor: win-executor
    environment:
        VERSION: 1.0.0     
    steps:
       - checkout
       - run: 
          name: "Pack"
          command: dotnet pack src/AutoPocoIO/AutoPocoIO.csproj -p:PackageVersion="$env:VERSION-beta.$env:CIRCLE_BUILD_NUM"
       - run:
          name: "Pack MSSql"
          command: dotnet pack src/AutoPocoIO.MsSql/AutoPocoIO.MsSql.csproj -p:PackageVersion="$env:VERSION-beta.$env:CIRCLE_BUILD_NUM"
       - run:
          name: "Nuget Push"
          command: dotnet nuget push "src/AutoPocoIO/bin/Debug/AutoPocoIO.$env:VERSION-beta.$env:CIRCLE_BUILD_NUM.nupkg" --source "github"
       - run:
          name: "Nuget Push MsSql"
          command: dotnet nuget push "src/AutoPocoIO.MsSql/bin/Debug/AutoPocoIO.MsSql.$env:VERSION-beta.$env:CIRCLE_BUILD_NUM.nupkg" --source "github"

  
workflows:
  build_deploy:
    jobs:
      - test-framework
      - deploy:
         requires:
            - test-framework
         filters:
            branches:
               only: master
