// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace AutoPocoIO.Migrations
{
    [DbContext(typeof(AppMigrationContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AutoPoco.Models.Connector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConnectionString");

                    b.Property<string>("DataSource")
                        .HasMaxLength(500);

                    b.Property<string>("InitialCatalog")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<int>("RecordLimit");

                    b.Property<int>("ResourceType");

                    b.Property<string>("Schema")
                        .HasMaxLength(50);

                    b.Property<string>("UserId")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("IDX_ConnectorName")
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Connector", "AutoPoco");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConnectionString = "",
                            Name = "appDb",
                            RecordLimit = 500,
                            ResourceType = 1,
                            Schema = "AutoPoco"
                        },
                        new
                        {
                            Id = 2,
                            ConnectionString = "",
                            Name = "logDb",
                            RecordLimit = 500,
                            ResourceType = 1,
                            Schema = "AutoPocoLog"
                        });
                });

            modelBuilder.Entity("AutoPoco.Models.UserJoin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("FKColumn")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<int?>("FKConnectorId");

                    b.Property<string>("FKTableName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("PKColumn")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<int?>("PKConnectorId");

                    b.Property<string>("PKTableName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("Alias")
                        .IsUnique();

                    b.HasIndex("FKConnectorId");

                    b.HasIndex("PKConnectorId");

                    b.ToTable("UserJoin", "AutoPoco");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alias = "Response",
                            FKColumn = "ResponseId,RequestGuid",
                            FKConnectorId = 2,
                            FKTableName = "Response",
                            PKColumn = "RequestId,RequestGuid",
                            PKConnectorId = 2,
                            PKTableName = "Request"
                        });
                });

            modelBuilder.Entity("AutoPoco.Models.UserJoin", b =>
                {
                    b.HasOne("AutoPoco.Models.Connector", "FKConnector")
                        .WithMany()
                        .HasForeignKey("FKConnectorId");

                    b.HasOne("AutoPoco.Models.Connector", "PKConnector")
                        .WithMany()
                        .HasForeignKey("PKConnectorId");
                });
#pragma warning restore 612, 618
        }
    }
}
