// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace AutoPocoIO.Migrations
{
    [DbContext(typeof(AppMigrationContext))]
    [Migration(MigrationNames.AppDb)]
    partial class AppDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
               .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("AutoPoco.Models.Connector", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128);

                    b.Property<string>("ConnectionString");

                    b.Property<string>("DataSource")
                        .HasMaxLength(500);

                    b.Property<string>("InitialCatalog")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<int>("RecordLimit");

                    b.Property<int>("ResourceType");

                    b.Property<int?>("Port");

                    b.Property<string>("Schema")
                        .HasMaxLength(50);

                    b.Property<string>("UserId")
                        .HasMaxLength(50);

                    b.Property<bool>("IsActive");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("IDX_ConnectorName")
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Connector", "AutoPoco");

                    b.HasData(
                        new
                        {
                            Id = "4b6b6ba7-0209-4b89-91cb-0e2a67aa37c1",
                            ConnectionString = "",
                            Name = "AppDb",
                            RecordLimit = 500,
                            ResourceType = 1,
                            Schema = "AutoPoco",
                            IsActive = true
                        },
                        new
                        {
                            Id = "4d74e770-54e9-4b0f-8f13-59ccb0808654",
                            ConnectionString = "",
                            Name = "LogDb",
                            RecordLimit = 500,
                            ResourceType = 1,
                            Schema = "AutoPocoLog",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("AutoPoco.Models.UserJoin", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128);

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("FKColumn")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("FKConnectorId")
                          .HasMaxLength(128);

                    b.Property<string>("FKTableName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("PKColumn")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("PKConnectorId")
                           .HasMaxLength(128);

                    b.Property<string>("PKTableName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("Alias")
                        .IsUnique();

                    b.HasIndex("FKConnectorId");

                    b.HasIndex("PKConnectorId");

                    b.ToTable("UserJoin","AutoPoco");

                    b.HasData(
                        new
                        {
                            Id = "abd7f037-cc34-44fb-89f5-2e4a06772a01",
                            Alias = "Response",
                            FKColumn = "ResponseId,RequestGuid",
                            FKConnectorId = "4d74e770-54e9-4b0f-8f13-59ccb0808654",
                            FKTableName = "Response",
                            PKColumn = "RequestId,RequestGuid",
                            PKConnectorId = "4d74e770-54e9-4b0f-8f13-59ccb0808654",
                            PKTableName = "Request"
                        });
                });

            modelBuilder.Entity("AutoPoco.Models.UserJoin", b =>
                {
                    b.HasOne("AutoPoco.Models.Connector", "FKConnector")
                        .WithMany()
                        .HasForeignKey("FKConnectorId");

                    b.HasOne("AutoPoco.Models.Connector", "PKConnector")
                        .WithMany()
                        .HasForeignKey("PKConnectorId");
                });
#pragma warning restore 612, 618
        }
    }
}
